import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";

export default function Home() {
  const user = useUser();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="flex flex-col text-white">
          {user.isSignedIn ? (
            <SignOutButton>Sign Out</SignOutButton>
          ) : (
            <SignInButton>Sign In</SignInButton>
          )}
        </div>
      </main>
    </>
  );
}
